In [1]:
from pathlib import Path

import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

In [2]:
IMAGE_LIST_PATH = '../data/train'

IMAGE_SAVE_PATH = '../data/annotations/all_list.csv'
TRAIN_SAVE_PATH = '../data/annotations/train.csv'
VAL_SAVE_PATH = '../data/annotations/val.csv'

In [3]:
image_list = os.listdir(IMAGE_LIST_PATH)

In [4]:
image_list

['cat.10953.jpg',
 'cat.4956.jpg',
 'dog.1237.jpg',
 'dog.4740.jpg',
 'dog.1622.jpg',
 'cat.6850.jpg',
 'cat.4806.jpg',
 'dog.2230.jpg',
 'cat.10471.jpg',
 'cat.1354.jpg',
 'cat.10281.jpg',
 'cat.2855.jpg',
 'cat.3636.jpg',
 'cat.355.jpg',
 'dog.9938.jpg',
 'dog.12479.jpg',
 'cat.4912.jpg',
 'cat.9239.jpg',
 'cat.2821.jpg',
 'cat.4961.jpg',
 'cat.10663.jpg',
 'dog.1816.jpg',
 'dog.2273.jpg',
 'dog.10941.jpg',
 'dog.8669.jpg',
 'dog.9980.jpg',
 'dog.4784.jpg',
 'cat.7528.jpg',
 'cat.1113.jpg',
 'cat.7695.jpg',
 'cat.658.jpg',
 'cat.5420.jpg',
 'cat.4964.jpg',
 'cat.10852.jpg',
 'dog.2275.jpg',
 'dog.4128.jpg',
 'cat.951.jpg',
 'cat.10146.jpg',
 'dog.617.jpg',
 'cat.4356.jpg',
 'dog.4193.jpg',
 'cat.7386.jpg',
 'cat.210.jpg',
 'dog.11948.jpg',
 'cat.5893.jpg',
 'dog.128.jpg',
 'dog.10639.jpg',
 'cat.3076.jpg',
 'cat.5437.jpg',
 'cat.1606.jpg',
 'cat.6589.jpg',
 'dog.7880.jpg',
 'cat.9566.jpg',
 'cat.4067.jpg',
 'cat.2784.jpg',
 'cat.2909.jpg',
 'dog.10142.jpg',
 'cat.10179.jpg',
 'cat.5913.jpg',
 'dog.11354.jpg',
 'cat.10098.jpg',
 'cat.7919.jpg',
 'dog.12311.jpg',
 'dog.8952.jpg',
 'cat.5188.jpg',
 'cat.5786.jpg',
 'cat.4451.jpg',
 'dog.6890.jpg',
 'cat.8580.jpg',
 'dog.1159.jpg',
 'dog.3696.jpg',
 'dog.8385.jpg',
 'cat.8784.jpg',
 'dog.6114.jpg',
 'dog.5129.jpg',
 'dog.6532.jpg',
 'dog.6856.jpg',
 'dog.11730.jpg',
 'cat.1041.jpg',
 'cat.10539.jpg',
 'cat.9883.jpg',
 'dog.4520.jpg',
 'dog.1429.jpg',
 'dog.6898.jpg',
 'dog.2664.jpg',
 'dog.8600.jpg',
 'dog.7482.jpg',
 'dog.7851.jpg',
 'cat.341.jpg',
 'cat.5875.jpg',
 'dog.4117.jpg',
 'dog.4757.jpg',
 'cat.3403.jpg',
 'cat.6170.jpg',
 'cat.2739.jpg',
 'dog.7223.jpg',
 'dog.9217.jpg',
 'cat.7779.jpg',
 'dog.2663.jpg',
 'cat.7943.jpg',
 'cat.1125.jpg',
 'dog.5537.jpg',
 'cat.994.jpg',
 'dog.1635.jpg',
 'dog.6725.jpg',
 'cat.6822.jpg',
 'cat.4943.jpg',
 'dog.3196.jpg',
 'cat.11780.jpg',
 'cat.3585.jpg',
 'dog.3471.jpg',
 'dog.5523.jpg',
 'dog.5775.jpg',
 'dog.5516.jpg',
 'cat.563.jpg',
 'cat.2673.jpg',
 'cat.6063.jpg',
 'cat.8446.jpg',
 'cat.12484.jpg',
 'cat.5813.jpg',
 'cat.2230.jpg',
 'cat.7575.jpg',
 'dog.4994.jpg',
 'cat.9956.jpg',
 'dog.6018.jpg',
 'dog.9776.jpg',
 'dog.8441.jpg',
 'cat.8127.jpg',
 'dog.10647.jpg',
 'cat.2061.jpg',
 'cat.3392.jpg',
 'dog.4524.jpg',
 'cat.5697.jpg',
 'cat.2807.jpg',
 'dog.3350.jpg',
 'cat.8709.jpg',
 'dog.4279.jpg',
 'cat.3347.jpg',
 'dog.2057.jpg',
 'cat.8511.jpg',
 'dog.5796.jpg',
 'cat.5076.jpg',
 'cat.11730.jpg',
 'dog.437.jpg',
 'cat.10497.jpg',
 'cat.10178.jpg',
 'dog.3307.jpg',
 'dog.5278.jpg',
 'dog.1032.jpg',
 'cat.9451.jpg',
 'dog.10544.jpg',
 'dog.1143.jpg',
 'cat.6396.jpg',
 'dog.9543.jpg',
 'dog.6071.jpg',
 'cat.5364.jpg',
 'dog.2655.jpg',
 'cat.10709.jpg',
 'cat.8856.jpg',
 'cat.6211.jpg',
 'dog.2990.jpg',
 'dog.5323.jpg',
 'dog.2816.jpg',
 'cat.10314.jpg',
 'cat.12325.jpg',
 'dog.4195.jpg',
 'dog.4275.jpg',
 'dog.2468.jpg',
 'cat.5563.jpg',
 'dog.9120.jpg',
 'cat.9039.jpg',
 'cat.5733.jpg',
 'dog.4312.jpg',
 'dog.7264.jpg',
 'cat.7373.jpg',
 'dog.4232.jpg',
 'dog.8190.jpg',
 'dog.1244.jpg',
 'dog.4528.jpg',
 'cat.1999.jpg',
 'dog.9973.jpg',
 'cat.7818.jpg',
 'dog.12316.jpg',
 'cat.592.jpg',
 'dog.3427.jpg',
 'cat.7770.jpg',
 'dog.8059.jpg',
 'cat.4156.jpg',
 'cat.2905.jpg',
 'dog.12455.jpg',
 'cat.10583.jpg',
 'dog.10621.jpg',
 'dog.3700.jpg',
 'cat.107.jpg',
 'cat.593.jpg',
 'dog.10813.jpg',
 'dog.1845.jpg',
 'dog.8549.jpg',
 'dog.9173.jpg',
 'cat.4044.jpg',
 'cat.3028.jpg',
 'dog.7165.jpg',
 'dog.8966.jpg',
 'cat.559.jpg',
 'cat.384.jpg',
 'dog.8044.jpg',
 'cat.7793.jpg',
 'cat.11491.jpg',
 'cat.1231.jpg',
 'dog.7289.jpg',
 'dog.11073.jpg',
 'cat.2761.jpg',
 'dog.49.jpg',
 'cat.11087.jpg',
 'cat.10125.jpg',
 'dog.3717.jpg',
 'dog.12038.jpg',
 'dog.10822.jpg',
 'dog.1753.jpg',
 'dog.10672.jpg',
 'cat.1190.jpg',
 'dog.10490.jpg',
 'cat.7293.jpg',
 'dog.9052.jpg',
 'dog.4056.jpg',
 'cat.2344.jpg',
 'dog.9700.jpg',
 'cat.4819.jpg',
 'dog.9069.jpg',
 'cat.11290.jpg',
 'cat.4655.jpg',
 'cat.6366.jpg',
 'cat.7409.jpg',
 'cat.6069.jpg',
 'dog.2870.jpg',
 'dog.27.jpg',
 'cat.6839.jpg',
 'cat.4432.jpg',
 'cat.2314.jpg',
 'dog.928.jpg',
 'dog.11867.jpg',
 'dog.6395.jpg',
 'cat.7051.jpg',
 'dog.3515.jpg',
 'cat.9144.jpg',
 'dog.5626.jpg',
 'cat.9031.jpg',
 'dog.6404.jpg',
 'dog.3668.jpg',
 'cat.5965.jpg',
 'dog.12188.jpg',
 'cat.4202.jpg',
 'dog.8375.jpg',
 'cat.3577.jpg',
 'cat.2186.jpg',
 'dog.1872.jpg',
 'cat.9610.jpg',
 'cat.8706.jpg',
 'dog.12084.jpg',
 'cat.8273.jpg',
 'dog.10690.jpg',
 'dog.8592.jpg',
 'dog.10370.jpg',
 'dog.12052.jpg',
 'cat.11618.jpg',
 'cat.3768.jpg',
 'cat.2040.jpg',
 'dog.1683.jpg',
 'dog.6355.jpg',
 'dog.11502.jpg',
 'dog.4151.jpg',
 'dog.4456.jpg',
 'dog.608.jpg',
 'dog.8990.jpg',
 'cat.3159.jpg',
 'cat.6240.jpg',
 'cat.7193.jpg',
 'dog.7846.jpg',
 'dog.7758.jpg',
 'cat.4791.jpg',
 'cat.4448.jpg',
 'dog.12001.jpg',
 'cat.9689.jpg',
 'dog.9364.jpg',
 'cat.11472.jpg',
 'dog.12352.jpg',
 'cat.11894.jpg',
 'cat.9756.jpg',
 'cat.642.jpg',
 'cat.5009.jpg',
 'dog.9533.jpg',
 'cat.3640.jpg',
 'dog.3183.jpg',
 'cat.1891.jpg',
 'dog.7090.jpg',
 'cat.741.jpg',
 'cat.9974.jpg',
 'dog.1388.jpg',
 'cat.1213.jpg',
 'dog.5774.jpg',
 'dog.6908.jpg',
 'dog.4976.jpg',
 'cat.616.jpg',
 'cat.3637.jpg',
 'dog.6262.jpg',
 'dog.1537.jpg',
 'cat.9426.jpg',
 'cat.9538.jpg',
 'cat.1712.jpg',
 'cat.4944.jpg',
 'dog.3083.jpg',
 'cat.1821.jpg',
 'dog.11153.jpg',
 'dog.11967.jpg',
 'dog.7878.jpg',
 'dog.3762.jpg',
 'dog.9378.jpg',
 'cat.3572.jpg',
 'cat.8832.jpg',
 'dog.7277.jpg',
 'dog.4121.jpg',
 'dog.12278.jpg',
 'dog.4825.jpg',
 'cat.5156.jpg',
 'cat.2567.jpg',
 'cat.8629.jpg',
 'cat.9778.jpg',
 'dog.2095.jpg',
 'dog.341.jpg',
 'cat.10095.jpg',
 'dog.4802.jpg',
 'cat.5331.jpg',
 'dog.4991.jpg',
 'cat.827.jpg',
 'cat.8775.jpg',
 'dog.1610.jpg',
 'dog.5183.jpg',
 'cat.3539.jpg',
 'dog.2405.jpg',
 'dog.12429.jpg',
 'dog.8772.jpg',
 'cat.3817.jpg',
 'dog.10764.jpg',
 'dog.8601.jpg',
 'dog.1520.jpg',
 'cat.1133.jpg',
 'dog.4148.jpg',
 'dog.7310.jpg',
 'dog.6602.jpg',
 'dog.6507.jpg',
 'dog.9013.jpg',
 'dog.9965.jpg',
 'dog.2607.jpg',
 'dog.4909.jpg',
 'dog.12411.jpg',
 'dog.9457.jpg',
 'cat.4648.jpg',
 'cat.10943.jpg',
 'cat.1402.jpg',
 'dog.12078.jpg',
 'cat.6161.jpg',
 'cat.7753.jpg',
 'cat.2605.jpg',
 'cat.8326.jpg',
 'cat.12133.jpg',
 'dog.3317.jpg',
 'cat.6562.jpg',
 'dog.6502.jpg',
 'cat.11929.jpg',
 'dog.5651.jpg',
 'dog.3401.jpg',
 'dog.756.jpg',
 'cat.7977.jpg',
 'dog.8287.jpg',
 'cat.9090.jpg',
 'dog.4086.jpg',
 'cat.1995.jpg',
 'dog.11975.jpg',
 'cat.4270.jpg',
 'cat.10532.jpg',
 'dog.2609.jpg',
 'cat.12222.jpg',
 'cat.11756.jpg',
 'dog.5013.jpg',
 'cat.11193.jpg',
 'dog.7439.jpg',
 'dog.7709.jpg',
 'dog.6277.jpg',
 'cat.5195.jpg',
 'cat.11636.jpg',
 'cat.2044.jpg',
 'cat.743.jpg',
 'dog.2444.jpg',
 'cat.500.jpg',
 'dog.743.jpg',
 'dog.11322.jpg',
 'cat.10965.jpg',
 'cat.1887.jpg',
 'dog.11719.jpg',
 'cat.4848.jpg',
 'cat.2895.jpg',
 'cat.9454.jpg',
 'cat.1849.jpg',
 'cat.7629.jpg',
 'cat.7245.jpg',
 'dog.2540.jpg',
 'cat.5003.jpg',
 'dog.2080.jpg',
 'cat.11129.jpg',
 'cat.4324.jpg',
 'cat.2998.jpg',
 'dog.4971.jpg',
 'dog.9075.jpg',
 'cat.9352.jpg',
 'cat.11089.jpg',
 'cat.3348.jpg',
 'dog.6402.jpg',
 'dog.11009.jpg',
 'cat.7385.jpg',
 'cat.10718.jpg',
 'dog.11734.jpg',
 'cat.5044.jpg',
 'cat.12146.jpg',
 'dog.10707.jpg',
 'cat.7257.jpg',
 'cat.4706.jpg',
 'cat.574.jpg',
 'cat.8518.jpg',
 'dog.3676.jpg',
 'cat.1349.jpg',
 'cat.3879.jpg',
 'dog.10927.jpg',
 'cat.3847.jpg',
 'dog.3693.jpg',
 'cat.3248.jpg',
 'dog.11829.jpg',
 'cat.3200.jpg',
 'dog.62.jpg',
 'dog.11705.jpg',
 'dog.3185.jpg',
 'dog.3951.jpg',
 'dog.1040.jpg',
 'dog.11449.jpg',
 'dog.1353.jpg',
 'cat.5097.jpg',
 'cat.5744.jpg',
 'cat.2782.jpg',
 'cat.9067.jpg',
 'cat.4172.jpg',
 'dog.2988.jpg',
 'dog.2611.jpg',
 'cat.1760.jpg',
 'cat.5307.jpg',
 'cat.4142.jpg',
 'cat.8153.jpg',
 'cat.6264.jpg',
 'dog.7158.jpg',
 'dog.10307.jpg',
 'dog.4686.jpg',
 'cat.3964.jpg',
 'cat.7287.jpg',
 'cat.9603.jpg',
 'dog.7020.jpg',
 'dog.6708.jpg',
 'dog.6787.jpg',
 'cat.9569.jpg',
 'dog.59.jpg',
 'cat.7967.jpg',
 'cat.713.jpg',
 'cat.4892.jpg',
 'cat.9624.jpg',
 'dog.8555.jpg',
 'cat.2941.jpg',
 'dog.3233.jpg',
 'cat.6183.jpg',
 'dog.3924.jpg',
 'cat.8515.jpg',
 'cat.7920.jpg',
 'dog.4092.jpg',
 'cat.470.jpg',
 'dog.8898.jpg',
 'dog.9477.jpg',
 'cat.7634.jpg',
 'cat.2520.jpg',
 'dog.10904.jpg',
 'cat.9471.jpg',
 'cat.11425.jpg',
 'cat.12027.jpg',
 'cat.1535.jpg',
 'cat.9121.jpg',
 'dog.8454.jpg',
 'dog.10400.jpg',
 'dog.1386.jpg',
 'dog.6611.jpg',
 'dog.181.jpg',
 'cat.10863.jpg',
 'cat.3820.jpg',
 'dog.9107.jpg',
 'cat.1940.jpg',
 'dog.7671.jpg',
 'dog.7524.jpg',
 'cat.5679.jpg',
 'dog.4819.jpg',
 'dog.5460.jpg',
 'cat.1296.jpg',
 'cat.3531.jpg',
 'cat.2694.jpg',
 'dog.1667.jpg',
 'cat.3069.jpg',
 'cat.7198.jpg',
 'cat.2795.jpg',
 'cat.4596.jpg',
 'cat.5236.jpg',
 'cat.10482.jpg',
 'dog.11158.jpg',
 'cat.5996.jpg',
 'dog.6901.jpg',
 'cat.4410.jpg',
 'cat.8652.jpg',
 'dog.9012.jpg',
 'dog.3663.jpg',
 'cat.3397.jpg',
 'dog.10054.jpg',
 'cat.995.jpg',
 'dog.4579.jpg',
 'dog.4353.jpg',
 'cat.5040.jpg',
 'dog.4732.jpg',
 'cat.2479.jpg',
 'dog.6897.jpg',
 'dog.9091.jpg',
 'dog.2852.jpg',
 'cat.3012.jpg',
 'dog.3165.jpg',
 'dog.2330.jpg',
 'dog.3845.jpg',
 'dog.951.jpg',
 'cat.2708.jpg',
 'cat.6136.jpg',
 'dog.4606.jpg',
 'cat.2613.jpg',
 'cat.311.jpg',
 'cat.3165.jpg',
 'cat.11265.jpg',
 'cat.2463.jpg',
 'dog.1545.jpg',
 'cat.8504.jpg',
 'cat.10446.jpg',
 'dog.8509.jpg',
 'dog.1608.jpg',
 'dog.4110.jpg',
 'dog.8573.jpg',
 'dog.8748.jpg',
 'cat.9445.jpg',
 'cat.2645.jpg',
 'cat.8056.jpg',
 'dog.9631.jpg',
 'dog.10717.jpg',
 'cat.11783.jpg',
 'cat.8845.jpg',
 'cat.4014.jpg',
 'cat.6757.jpg',
 'dog.11245.jpg',
 'cat.3674.jpg',
 'dog.10168.jpg',
 'dog.6513.jpg',
 'dog.307.jpg',
 'dog.3210.jpg',
 'dog.6261.jpg',
 'cat.4055.jpg',
 'dog.8032.jpg',
 'dog.3416.jpg',
 'cat.8347.jpg',
 'dog.12385.jpg',
 'dog.7468.jpg',
 'dog.7097.jpg',
 'dog.7054.jpg',
 'dog.7921.jpg',
 'dog.6592.jpg',
 'dog.8414.jpg',
 'cat.3676.jpg',
 'dog.4428.jpg',
 'dog.11268.jpg',
 'cat.3231.jpg',
 'dog.11851.jpg',
 'dog.3578.jpg',
 'cat.21.jpg',
 'dog.10517.jpg',
 'cat.4240.jpg',
 'dog.3268.jpg',
 'cat.7400.jpg',
 'cat.5216.jpg',
 'dog.1586.jpg',
 'dog.7404.jpg',
 'cat.9602.jpg',
 'dog.1764.jpg',
 'cat.12174.jpg',
 'dog.668.jpg',
 'dog.8711.jpg',
 'dog.7882.jpg',
 'cat.11382.jpg',
 'cat.5413.jpg',
 'cat.3052.jpg',
 'dog.12007.jpg',
 'dog.829.jpg',
 'cat.1645.jpg',
 'cat.7728.jpg',
 'cat.1035.jpg',
 'dog.1896.jpg',
 'cat.7021.jpg',
 'dog.747.jpg',
 'cat.5809.jpg',
 'cat.3376.jpg',
 'dog.1271.jpg',
 'cat.8131.jpg',
 'dog.6889.jpg',
 'cat.8074.jpg',
 'cat.6328.jpg',
 'cat.11219.jpg',
 'dog.1073.jpg',
 'cat.9477.jpg',
 'dog.3592.jpg',
 'dog.12002.jpg',
 'cat.5858.jpg',
 'dog.4667.jpg',
 'dog.7643.jpg',
 'dog.11634.jpg',
 'cat.2820.jpg',
 'dog.5802.jpg',
 'dog.1983.jpg',
 'cat.5883.jpg',
 'dog.1498.jpg',
 'dog.8762.jpg',
 'cat.3314.jpg',
 'cat.10290.jpg',
 'dog.11986.jpg',
 'dog.11852.jpg',
 'cat.929.jpg',
 'cat.3273.jpg',
 'cat.773.jpg',
 'cat.2004.jpg',
 'dog.10885.jpg',
 'cat.170.jpg',
 'dog.6462.jpg',
 'dog.9699.jpg',
 'cat.8334.jpg',
 'cat.5776.jpg',
 'cat.7661.jpg',
 'cat.1061.jpg',
 'cat.9931.jpg',
 'dog.8033.jpg',
 'cat.11440.jpg',
 'cat.10871.jpg',
 'cat.3509.jpg',
 'dog.2309.jpg',
 'dog.3761.jpg',
 'dog.6054.jpg',
 'dog.5517.jpg',
 'dog.6450.jpg',
 'cat.5788.jpg',
 'cat.10351.jpg',
 'cat.5499.jpg',
 'cat.3596.jpg',
 'cat.11791.jpg',
 'dog.759.jpg',
 'cat.2048.jpg',
 'cat.7284.jpg',
 'cat.2972.jpg',
 'dog.4838.jpg',
 'dog.7294.jpg',
 'dog.5407.jpg',
 'dog.10887.jpg',
 'dog.8887.jpg',
 'cat.7559.jpg',
 'dog.10606.jpg',
 'dog.281.jpg',
 'dog.10332.jpg',
 'dog.2575.jpg',
 'cat.10308.jpg',
 'cat.1623.jpg',
 'dog.2347.jpg',
 'dog.10560.jpg',
 'cat.6675.jpg',
 'dog.8589.jpg',
 'dog.4670.jpg',
 'cat.3698.jpg',
 'dog.11538.jpg',
 'dog.7437.jpg',
 'dog.12369.jpg',
 'dog.4387.jpg',
 'cat.7554.jpg',
 'cat.4166.jpg',
 'cat.4703.jpg',
 'dog.6962.jpg',
 'dog.4575.jpg',
 'cat.6588.jpg',
 'cat.427.jpg',
 'cat.5765.jpg',
 'dog.9766.jpg',
 'dog.2651.jpg',
 'dog.4294.jpg',
 'cat.6112.jpg',
 'cat.9949.jpg',
 'dog.877.jpg',
 'dog.10692.jpg',
 'dog.6956.jpg',
 'dog.3552.jpg',
 'cat.4095.jpg',
 'dog.10590.jpg',
 'cat.7387.jpg',
 'dog.570.jpg',
 'dog.10316.jpg',
 'dog.5664.jpg',
 'dog.8431.jpg',
 'cat.4221.jpg',
 'cat.11247.jpg',
 'dog.3175.jpg',
 'dog.10553.jpg',
 'dog.409.jpg',
 'dog.6358.jpg',
 'dog.4922.jpg',
 'dog.7375.jpg',
 'cat.6788.jpg',
 'cat.11370.jpg',
 'dog.12250.jpg',
 'dog.7055.jpg',
 'dog.5812.jpg',
 'cat.6337.jpg',
 'cat.4194.jpg',
 'dog.11231.jpg',
 'cat.10503.jpg',
 'cat.2136.jpg',
 'dog.7560.jpg',
 'dog.10559.jpg',
 'cat.2729.jpg',
 'cat.9155.jpg',
 'cat.7772.jpg',
 'dog.8580.jpg',
 'dog.11758.jpg',
 'dog.8339.jpg',
 'dog.469.jpg',
 'cat.9557.jpg',
 'dog.6455.jpg',
 'cat.1547.jpg',
 'dog.4037.jpg',
 'cat.7018.jpg',
 'dog.5406.jpg',
 'cat.8415.jpg',
 'dog.10893.jpg',
 'cat.7440.jpg',
 'cat.9729.jpg',
 'cat.8533.jpg',
 'dog.4938.jpg',
 'dog.5483.jpg',
 'cat.12094.jpg',
 'dog.7533.jpg',
 'dog.5929.jpg',
 'cat.8602.jpg',
 'cat.1752.jpg',
 'dog.3566.jpg',
 'dog.652.jpg',
 'dog.11899.jpg',
 'dog.1370.jpg',
 'cat.8976.jpg',
 'cat.5771.jpg',
 'cat.11405.jpg',
 'cat.8337.jpg',
 'cat.5884.jpg',
 'cat.1363.jpg',
 'cat.12352.jpg',
 'dog.7385.jpg',
 'dog.12220.jpg',
 'cat.1817.jpg',
 'cat.12144.jpg',
 'cat.8380.jpg',
 'cat.401.jpg',
 'cat.5206.jpg',
 'dog.3093.jpg',
 'cat.1633.jpg',
 'dog.3431.jpg',
 'cat.6031.jpg',
 'cat.4077.jpg',
 'dog.1796.jpg',
 'cat.6881.jpg',
 'cat.4871.jpg',
 'dog.1532.jpg',
 'cat.7696.jpg',
 'dog.2147.jpg',
 'dog.7303.jpg',
 'dog.8876.jpg',
 'dog.4660.jpg',
 'dog.6545.jpg',
 'dog.11363.jpg',
 'cat.4495.jpg',
 'cat.4405.jpg',
 'dog.6466.jpg',
 'cat.8111.jpg',
 'dog.11935.jpg',
 'cat.4002.jpg',
 'cat.12124.jpg',
 'cat.10431.jpg',
 'cat.3317.jpg',
 'cat.899.jpg',
 'cat.5159.jpg',
 'cat.5527.jpg',
 'cat.5794.jpg',
 'cat.10485.jpg',
 'dog.9422.jpg',
 'dog.9826.jpg',
 'dog.6824.jpg',
 'cat.6679.jpg',
 'dog.5721.jpg',
 'cat.3687.jpg',
 'dog.1094.jpg',
 'dog.3805.jpg',
 'cat.9443.jpg',
 'cat.585.jpg',
 'cat.6403.jpg',
 'cat.7682.jpg',
 'cat.3473.jpg',
 'cat.892.jpg',
 'cat.11391.jpg',
 'dog.647.jpg',
 'cat.815.jpg',
 'cat.5022.jpg',
 'cat.11522.jpg',
 'cat.6390.jpg',
 'dog.8704.jpg',
 'dog.2333.jpg',
 'dog.9263.jpg',
 'dog.4283.jpg',
 'cat.12050.jpg',
 'cat.10263.jpg',
 'dog.3381.jpg',
 'cat.8175.jpg',
 'dog.6480.jpg',
 'dog.9922.jpg',
 'cat.4100.jpg',
 'cat.11650.jpg',
 'cat.8927.jpg',
 'dog.7625.jpg',
 'dog.6108.jpg',
 'cat.2535.jpg',
 'dog.6593.jpg',
 'cat.12452.jpg',
 'dog.9622.jpg',
 'dog.6339.jpg',
 'cat.5831.jpg',
 'cat.1951.jpg',
 'dog.3865.jpg',
 'dog.538.jpg',
 'dog.2720.jpg',
 'dog.6123.jpg',
 'cat.8778.jpg',
 'dog.1097.jpg',
 'cat.6419.jpg',
 'dog.11669.jpg',
 'cat.10392.jpg',
 'cat.6508.jpg',
 'cat.4845.jpg',
 'dog.11684.jpg',
 'dog.6482.jpg',
 'cat.10082.jpg',
 'cat.7569.jpg',
 'dog.2614.jpg',
 'cat.250.jpg',
 'dog.5391.jpg',
 'cat.498.jpg',
 'dog.8218.jpg',
 'cat.3932.jpg',
 'dog.9140.jpg',
 'dog.11020.jpg',
 'cat.9520.jpg',
 'cat.10473.jpg',
 'dog.3759.jpg',
 'cat.749.jpg',
 'dog.6201.jpg',
 'dog.1727.jpg',
 'cat.10672.jpg',
 'cat.8318.jpg',
 'cat.6028.jpg',
 'dog.9488.jpg',
 'cat.6962.jpg',
 'cat.4794.jpg',
 'dog.4038.jpg',
 'dog.5959.jpg',
 'dog.11655.jpg',
 'cat.5495.jpg',
 'cat.11658.jpg',
 'cat.4108.jpg',
 'cat.4855.jpg',
 'cat.9253.jpg',
 'cat.7867.jpg',
 'dog.11166.jpg',
 'dog.6546.jpg',
 'dog.12273.jpg',
 'cat.467.jpg',
 'dog.9393.jpg',
 'cat.11284.jpg',
 'dog.4040.jpg',
 'dog.9598.jpg',
 'cat.5392.jpg',
 'cat.10302.jpg',
 'dog.6209.jpg',
 'cat.1470.jpg',
 'cat.4560.jpg',
 'cat.9962.jpg',
 'cat.6457.jpg',
 'dog.6368.jpg',
 'cat.6966.jpg',
 'cat.1596.jpg',
 'cat.4427.jpg',
 'cat.9570.jpg',
 'dog.8401.jpg',
 'cat.3390.jpg',
 'cat.12256.jpg',
 'cat.1142.jpg',
 'cat.4657.jpg',
 'dog.4772.jpg',
 'cat.6691.jpg',
 'cat.8938.jpg',
 'cat.8631.jpg',
 'dog.11833.jpg',
 'cat.9514.jpg',
 'cat.6723.jpg',
 'cat.5897.jpg',
 'cat.9682.jpg',
 'dog.7516.jpg',
 'cat.20.jpg',
 'dog.1066.jpg',
 'cat.10389.jpg',
 'cat.12229.jpg',
 'dog.10835.jpg',
 'cat.9819.jpg',
 'dog.6401.jpg',
 'dog.7976.jpg',
 'dog.8060.jpg',
 'cat.1286.jpg',
 'cat.4125.jpg',
 'cat.8774.jpg',
 'cat.8670.jpg',
 'dog.2050.jpg',
 'dog.11875.jpg',
 'dog.12165.jpg',
 'dog.9110.jpg',
 'dog.3481.jpg',
 'dog.2012.jpg',
 'cat.7799.jpg',
 'cat.10062.jpg',
 'cat.6865.jpg',
 'cat.10973.jpg',
 'dog.10968.jpg',
 'cat.11822.jpg',
 'dog.10262.jpg',
 'dog.107.jpg',
 'cat.584.jpg',
 'dog.3722.jpg',
 'dog.535.jpg',
 'dog.9676.jpg',
 'dog.704.jpg',
 'cat.11041.jpg',
 'dog.1797.jpg',
 'cat.9511.jpg',
 'cat.7896.jpg',
 'dog.7325.jpg',
 'dog.8881.jpg',
 'cat.5685.jpg',
 'dog.7545.jpg',
 'cat.4291.jpg',
 'dog.119.jpg',
 'dog.3365.jpg',
 'cat.3781.jpg',
 'dog.183.jpg',
 'cat.43.jpg',
 'dog.6352.jpg',
 'dog.10324.jpg',
 'cat.7546.jpg',
 'cat.2302.jpg',
 'dog.3100.jpg',
 'dog.10410.jpg',
 'cat.10230.jpg',
 'dog.6882.jpg',
 'cat.2025.jpg',
 'cat.10156.jpg',
 'cat.3055.jpg',
 'cat.488.jpg',
 'dog.3348.jpg',
 'dog.1406.jpg',
 'cat.1631.jpg',
 'cat.2932.jpg',
 'dog.11628.jpg',
 'cat.1271.jpg',
 'cat.3868.jpg',
 'cat.10104.jpg',
 'cat.539.jpg',
 'cat.11324.jpg',
 'dog.5818.jpg',
 'dog.10024.jpg',
 'dog.3918.jpg',
 'dog.8523.jpg',
 ...]

In [5]:
labels = []
for image in image_list:
    label = image[:3]
    if label == 'cat':
        label = 0
    else:
        label = 1
    labels.append(label)

In [6]:
labels

[0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 ...]

In [7]:
all_image_with_label_df = pd.DataFrame({
    'image_name': image_list,
    'label': labels
})

In [8]:
all_image_with_label_df

          image_name  label
0      cat.10953.jpg      0
1       cat.4956.jpg      0
2       dog.1237.jpg      1
3       dog.4740.jpg      1
4       dog.1622.jpg      1
...              ...    ...
24995   cat.2839.jpg      0
24996   cat.7831.jpg      0
24997   dog.2246.jpg      1
24998  dog.10465.jpg      1
24999   dog.4003.jpg      1

[25000 rows x 2 columns]

In [9]:
all_image_with_label_df.to_csv(IMAGE_SAVE_PATH)

In [11]:
cat_df = all_image_with_label_df.loc[all_image_with_label_df['label'] == 0]

In [12]:
cat_df

          image_name  label
0      cat.10953.jpg      0
1       cat.4956.jpg      0
5       cat.6850.jpg      0
6       cat.4806.jpg      0
8      cat.10471.jpg      0
...              ...    ...
24990   cat.1971.jpg      0
24992   cat.2110.jpg      0
24993  cat.12176.jpg      0
24995   cat.2839.jpg      0
24996   cat.7831.jpg      0

[12500 rows x 2 columns]

In [13]:
dog_df = all_image_with_label_df.loc[all_image_with_label_df['label'] == 1]

In [14]:
dog_df

          image_name  label
2       dog.1237.jpg      1
3       dog.4740.jpg      1
4       dog.1622.jpg      1
7       dog.2230.jpg      1
14      dog.9938.jpg      1
...              ...    ...
24991   dog.2981.jpg      1
24994   dog.8516.jpg      1
24997   dog.2246.jpg      1
24998  dog.10465.jpg      1
24999   dog.4003.jpg      1

[12500 rows x 2 columns]

In [18]:
int(len(cat_df['label'])*0.8)

10000

In [19]:
train_cat_df = cat_df.iloc[:int(0.8*len(cat_df['label']))]

In [20]:
train_cat_df

          image_name  label
0      cat.10953.jpg      0
1       cat.4956.jpg      0
5       cat.6850.jpg      0
6       cat.4806.jpg      0
8      cat.10471.jpg      0
...              ...    ...
19943   cat.9496.jpg      0
19944   cat.7428.jpg      0
19949   cat.3552.jpg      0
19952   cat.2116.jpg      0
19955  cat.11845.jpg      0

[10000 rows x 2 columns]

In [21]:
train_dog_df = dog_df.iloc[:int(0.8*len(dog_df['label']))]

In [22]:
train_dog_df

          image_name  label
2       dog.1237.jpg      1
3       dog.4740.jpg      1
4       dog.1622.jpg      1
7       dog.2230.jpg      1
14      dog.9938.jpg      1
...              ...    ...
20034  dog.11133.jpg      1
20037  dog.12413.jpg      1
20038  dog.11586.jpg      1
20043   dog.2062.jpg      1
20045   dog.3159.jpg      1

[10000 rows x 2 columns]

In [24]:
val_cat_df = cat_df.iloc[int(0.8*len(cat_df['label'])):]

In [25]:
val_cat_df

          image_name  label
19957   cat.2021.jpg      0
19958   cat.8222.jpg      0
19959   cat.5197.jpg      0
19962   cat.5450.jpg      0
19964  cat.10932.jpg      0
...              ...    ...
24990   cat.1971.jpg      0
24992   cat.2110.jpg      0
24993  cat.12176.jpg      0
24995   cat.2839.jpg      0
24996   cat.7831.jpg      0

[2500 rows x 2 columns]

In [26]:
val_dog_df = dog_df.iloc[int(0.8*len(dog_df['label'])):]

In [27]:
val_dog_df

          image_name  label
20046   dog.7440.jpg      1
20047   dog.4620.jpg      1
20049  dog.10939.jpg      1
20051   dog.8498.jpg      1
20055   dog.7278.jpg      1
...              ...    ...
24991   dog.2981.jpg      1
24994   dog.8516.jpg      1
24997   dog.2246.jpg      1
24998  dog.10465.jpg      1
24999   dog.4003.jpg      1

[2500 rows x 2 columns]

In [30]:
val_df = pd.concat([val_cat_df, val_dog_df])

In [31]:
val_df

          image_name  label
19957   cat.2021.jpg      0
19958   cat.8222.jpg      0
19959   cat.5197.jpg      0
19962   cat.5450.jpg      0
19964  cat.10932.jpg      0
...              ...    ...
24991   dog.2981.jpg      1
24994   dog.8516.jpg      1
24997   dog.2246.jpg      1
24998  dog.10465.jpg      1
24999   dog.4003.jpg      1

[5000 rows x 2 columns]

In [32]:
train_df = pd.concat([train_cat_df, train_dog_df])

In [33]:
train_df

          image_name  label
0      cat.10953.jpg      0
1       cat.4956.jpg      0
5       cat.6850.jpg      0
6       cat.4806.jpg      0
8      cat.10471.jpg      0
...              ...    ...
20034  dog.11133.jpg      1
20037  dog.12413.jpg      1
20038  dog.11586.jpg      1
20043   dog.2062.jpg      1
20045   dog.3159.jpg      1

[20000 rows x 2 columns]

In [ ]:
val_df.to_csv()